import { authConfig } from './config.js?v=4';
import { validTask, normalizeDue } from './core.js?v=14';
let client=null,user=null,revision=0,loading=false,writing=false,generation=0;
const $=s=>document.querySelector(s);
export async function initializeAccount({onState,notify,getLocalTasks}) {
 const configured=Boolean(authConfig.supabaseUrl&&authConfig.supabasePublishableKey);
 let mode='login';
 function message(text){$('#auth-message').textContent=text;}
 function modeUI(){const signup=mode==='signup';$('#auth-title').textContent=signup?'Create your account':'Welcome back';$('#auth-submit').textContent=signup?'Create account':'Sign in';$('#auth-password').autocomplete=signup?'new-password':'current-password';$('#auth-switch').textContent=signup?'Already have an account? Sign in':'New here? Create an account';$('#auth-password').required=mode!=='reset';}
 $('#account-button').onclick=()=>{mode='login';modeUI();message(configured?'':'Account sign-in is not configured yet. You can continue using this browser.');$('#auth-dialog').showModal();};
 $('#auth-close').onclick=()=>$('#auth-dialog').close();
 $('#auth-switch').onclick=()=>{mode=mode==='signup'?'login':'signup';modeUI();message(configured?'':'Account sign-in is not configured yet. You can continue using this browser.');};
 $('#auth-form').onsubmit=async e=>{e.preventDefault();if(!client)return message('The site owner needs to configure account sign-in first.');const email=$('#auth-email').value.trim(),password=$('#auth-password').value;$('#auth-submit').disabled=true;try{const result=mode==='signup'?await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}}):await client.auth.signInWithPassword({email,password});if(result.error)throw result.error;$('#auth-password').value='';if(mode==='signup'&&!result.data.session)message('Check your email to confirm your account, then sign in.');else $('#auth-dialog').close();}catch(error){message(error.message||'Sign-in failed. Please try again.');}finally{$('#auth-submit').disabled=false;}};
 $('#google-login').onclick=async()=>{if(!client)return message('Google sign-in is not configured yet.');const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname}});if(error)message(error.message);};
 $('#forgot-password').onclick=async()=>{if(!client)return message('Account sign-in is not configured yet.');const email=$('#auth-email').value.trim();if(!email)return message('Enter your email address first.');const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});message(error?error.message:'Check your email for a password reset link.');};
 $('#reset-form').onsubmit=async e=>{e.preventDefault();$('#reset-submit').disabled=true;try{const {error}=await client.auth.updateUser({password:$('#new-password').value});if(error)throw error;$('#new-password').value='';$('#reset-dialog').close();notify('Password updated.');}catch(error){$('#reset-message').textContent=error.message;}finally{$('#reset-submit').disabled=false;}};
 $('#reset-close').onclick=()=>$('#reset-dialog').close();
 $('#signout').onclick=async()=>{if(writing)return notify('Wait for your tasks to finish saving.');const {error}=await client.auth.signOut();if(error)notify(error.message);};
 $('#migrate-local').onclick=async()=>{const local=getLocalTasks();if(!local.length)return notify('No browser tasks to import.');if(!confirm(`Copy ${local.length} browser tasks into your account? Your browser copy will be kept.`))return;const existing=currentTasks;const merged=[...existing];for(const task of local){if(!merged.some(t=>t.id===task.id))merged.push(task);}if(await saveCloud(merged,notify)){currentTasks=merged;onState({user,tasks:merged,ready:true});notify('Browser tasks copied to your account.');}};
 if(!configured){$('#google-login').disabled=true;$('#auth-submit').disabled=true;$('#forgot-password').disabled=true;return;}
 async function load(session){const ticket=++generation;user=session?.user||null;loading=Boolean(user);$('#account-button').hidden=Boolean(user);$('#account-info').hidden=!user;$('#account-email').textContent=user?.email||'Your account';$('#storage-status').textContent=user?'Loading your cloud tasks…':'Saved in this browser';onState({user,tasks:[],ready:!user});if(!user){currentTasks=[];return;}
 try{let {data,error}=await client.from('calendar_state').select('tasks,revision').eq('user_id',user.id).maybeSingle();if(error)throw error;if(!data){const inserted=await client.from('calendar_state').insert({user_id:user.id,tasks:[],revision:0}).select('tasks,revision').single();if(inserted.error)throw inserted.error;data=inserted.data;}if(ticket!==generation)return;if(!Array.isArray(data.tasks)||!data.tasks.every(validTask))throw Error('Cloud tasks have an invalid format.');revision=data.revision;currentTasks=data.tasks.map(t=>({...t,due:normalizeDue(t.due)}));loading=false;$('#storage-status').textContent='Synced to your account';onState({user,tasks:currentTasks,ready:true});}catch(error){if(ticket!==generation)return;$('#storage-status').textContent='Cloud unavailable · editing paused';notify(`Could not load cloud tasks: ${error.message}`);}}
 try{const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.57.4');client=createClient(authConfig.supabaseUrl,authConfig.supabasePublishableKey);fetch(`${authConfig.supabaseUrl}/auth/v1/settings`,{headers:{apikey:authConfig.supabasePublishableKey}}).then(r=>r.ok?r.json():null).then(settings=>{if(settings?.external?.google===false){$('#google-login').disabled=true;$('#google-login').textContent='Google sign-in · coming soon';}}).catch(()=>{});client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY')$('#reset-dialog').showModal();if(event==='TOKEN_REFRESHED')return;setTimeout(()=>load(session),0);});}catch(error){notify('Account service could not start. Reload to try again.');$('#auth-submit').disabled=true;}
}
let currentTasks=[];
export async function saveCloud(tasks,notify){if(!client||!user||loading||writing){notify('Account is busy or unavailable. Try again shortly.');return false;}writing=true;const ticket=generation;const owner=user.id;$('#storage-status').textContent='Saving…';try{const {data,error}=await client.from('calendar_state').update({tasks,revision:revision+1}).eq('user_id',owner).eq('revision',revision).select('revision');if(error)throw error;if(!data?.length)throw Error('Tasks changed in another tab or device. Export your current tasks, then reload before editing.');if(ticket!==generation)return false;revision=data[0].revision;currentTasks=tasks;$('#storage-status').textContent='Synced to your account';return true;}catch(error){notify(`Could not save: ${error.message}`);$('#storage-status').textContent='Not saved · retry or reload';return false;}finally{writing=false;}}
