import {dateKey,validDate,validDeadline} from './core.js';
const zones={'Singapore Standard Time':'Asia/Singapore','China Standard Time':'Asia/Shanghai','Eastern Standard Time':'America/New_York','Pacific Standard Time':'America/Los_Angeles','GMT Standard Time':'Europe/London','UTC':'UTC'};
const unescape=s=>s.replace(/\\[nN]/g,'\n').replace(/\\([,;\\])/g,'$1');
function localValue(d){return `${dateKey(d)}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function parseDate(prop){if(!prop)throw Error('Missing start/deadline');const s=prop.value;if(/^\d{8}$/.test(s)){const value=`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}T23:59`;if(!validDate(value.slice(0,10)))throw Error('Invalid date');return value;}
 const match=s.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})?(Z)?$/);if(!match)throw Error('Unsupported date format');const [,y,m,d,h,min,sec='00',utc]=match;const wall=`${y}-${m}-${d}T${h}:${min}`;if(!validDate(wall.slice(0,10))||Number(h)>23||Number(min)>59||Number(sec)>59)throw Error('Invalid time');if(utc)return localValue(new Date(`${wall}:${sec}Z`));let zone=prop.zone;if(!zone){if(!validDeadline(wall))throw Error('Invalid local time');return wall;}zone=zones[zone]||zone;let fmt;try{fmt=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});}catch{throw Error(`Unsupported time zone: ${zone}`);}const target=Date.UTC(+y,+m-1,+d,+h,+min,+sec);let guess=target;for(let i=0;i<4;i++){const parts=Object.fromEntries(fmt.formatToParts(new Date(guess)).map(p=>[p.type,p.value]));const wallTime=Date.UTC(+parts.year,+parts.month-1,+parts.day,+parts.hour,+parts.minute,+parts.second);const delta=target-wallTime;if(delta===0)return localValue(new Date(guess));guess+=delta;}throw Error('Ambiguous or invalid time zone transition');}
export function parseCalendar(text){const lines=text.replace(/^\uFEFF/,'').replace(/\r\n/g,'\n').replace(/\n[ \t]/g,'').split('\n');if(!lines.some(l=>l==='BEGIN:VCALENDAR')||!lines.some(l=>l==='END:VCALENDAR'))throw Error('Choose an iCalendar (.ics) file.');const entries=[],skipped=[];let event=null,kind='',depth=0;
 for(const line of lines){if(/^BEGIN:(VEVENT|VTODO)$/.test(line)){event={};kind=line.slice(6);depth=0;continue;}if(!event)continue;if(line.startsWith('BEGIN:')){depth++;continue;}if(line===`END:${kind}`){try{if(event.RRULE||event.RDATE||event['RECURRENCE-ID'])throw Error('Recurring items are not imported yet');if(event.STATUS?.value==='CANCELLED')throw Error('Cancelled event');const date=kind==='VTODO'?(event.DUE||event.DTSTART):event.DTSTART;const due=parseDate(date);const title=unescape(event.SUMMARY?.value||'Untitled calendar item').slice(0,120);const notes=[unescape(event.DESCRIPTION?.value||''),event.LOCATION?`Location: ${unescape(event.LOCATION.value)}`:'','Imported from calendar.'].filter(Boolean).join('\n').slice(0,2000);const identity=`${event.UID?.value||title}|${kind}|${date?.value}|${date?.zone||''}`;entries.push({identity,title,due,notes,priority:'normal',completed:kind==='VTODO'&&event.STATUS?.value==='COMPLETED'});}catch(error){skipped.push(`${unescape(event.SUMMARY?.value||'Untitled item')}: ${error.message}`);}event=null;continue;}if(line.startsWith('END:')){depth--;continue;}if(depth)continue;const colon=line.indexOf(':');if(colon<0)continue;const head=line.slice(0,colon);const name=head.split(';')[0].toUpperCase();const zone=head.match(/;TZID=(?:"([^"]+)"|([^;]+))/i);event[name]={value:line.slice(colon+1),zone:zone?.[1]||zone?.[2]};}
 return {entries,skipped};}
export async function calendarTaskId(identity){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(identity));return 'ics-'+Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');}
