export function dateKey(d) { return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; }
export function validDate(s) { if(typeof s !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const [y,m,d]=s.split('-').map(Number);const value=new Date(0);value.setUTCFullYear(y,m-1,d);value.setUTCHours(0,0,0,0);return y>=1000 && y<=9999 && value.getUTCFullYear()===y && value.getUTCMonth()===m-1 && value.getUTCDate()===d; }
export function daysLeft(due, now=new Date()) { const [y,m,d]=due.slice(0,10).split('-').map(Number);return Math.round((Date.UTC(y,m-1,d)-Date.UTC(now.getFullYear(),now.getMonth(),now.getDate()))/86400000); }
export function validTask(t) { return t && typeof t.id==='string' && t.id.length>0 && typeof t.title==='string' && t.title.trim().length>0 && t.title.length<=120 && validDeadline(t.due) && ['normal','high','low'].includes(t.priority) && typeof t.notes==='string' && t.notes.length<=2000 && typeof t.completed==='boolean' && typeof t.createdAt==='string' && (t.images===undefined || (Array.isArray(t.images)&&t.images.length<=3&&t.images.every(x=>x&&typeof x.name==='string'&&x.name.length<=120&&typeof x.data==='string'&&x.data.length<=350000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(x.data)))); }
export function normalizeDue(due) { return due.length===10 ? `${due}T23:59` : due; }
export function validDeadline(s) { if(typeof s!=='string')return false;if(s.length===10)return validDate(s);if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(s)||!validDate(s.slice(0,10)))return false;const h=Number(s.slice(11,13)),m=Number(s.slice(14,16));if(h>23||m>59)return false;const d=new Date(s);return Number.isFinite(d.getTime())&&d.getHours()===h&&d.getMinutes()===m&&dateKey(d)===s.slice(0,10); }
export function millisecondsLeft(due,now=new Date()){return new Date(normalizeDue(due)).getTime()-now.getTime();}
export function countdown(due,now=new Date()){const ms=millisecondsLeft(due,now);const minutes=Math.ceil(Math.abs(ms)/60000);const days=Math.floor(minutes/1440),hours=Math.floor(minutes%1440/60),mins=minutes%60;const value=days?`${days}d ${hours}h`:hours?`${hours}h ${mins}m`:`${mins}m`;return {value:ms===0?'Now':`${ms<0?'-':''}${value}`,label:ms===0?'Due now':ms<0?'overdue':'left',overdue:ms<0};}
export function urgency(t,now=new Date()){if(t.completed)return 'completed';const ms=millisecondsLeft(t.due,now);if(ms<0)return 'overdue';if(t.due.slice(0,10)===dateKey(now))return 'today';if(ms<=3*86400000)return 'three';if(ms<=7*86400000)return 'week';return 'later';}
export function matchesFilters(t,{due='all',overdue='all',priority='all',customDays=7}={},now=new Date()){const ms=millisecondsLeft(t.due,now);if(priority!=='all'&&t.priority!==priority)return false;if(overdue==='yes'&&(t.completed||ms>=0))return false;if(overdue==='no'&&!t.completed&&ms<0)return false;if(due==='all')return true;if(t.completed||ms<0)return false;if(due==='today')return t.due.slice(0,10)===dateKey(now);const days=due==='custom'?customDays:Number(due);return ms<=days*86400000;}
